# .github/workflows/daily-trading-analysis.yml
name: Minervini SEPA Analysis Diario

on:
  schedule:
    # Ejecutar Lunes a Viernes 5 horas después del cierre del mercado US
    # Mercado US: 9:30 AM - 4:00 PM EST = 14:30 - 20:00 UTC (horario estándar)
    # Mercado US: 9:30 AM - 4:00 PM EDT = 13:30 - 19:00 UTC (horario de verano)
    - cron: '0 1 * * 2-6'   # 01:00 UTC = 5h después del cierre en horario estándar (Martes-Sábado UTC)
    - cron: '0 0 * * 2-6'   # 00:00 UTC = 5h después del cierre en horario de verano (Martes-Sábado UTC)
  workflow_dispatch:  # Permitir ejecución manual

# PERMISOS NECESARIOS PARA GITHUB PAGES
permissions:
  contents: read
  pages: write
  id-token: write

# Asegurar que solo un workflow corra a la vez
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  minervini-analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 240  # 4 horas máximo para análisis Minervini completo
    
    # Configurar entorno para GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Configurar Python y caché de dependencias
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
        
    - name: Instalar dependencias
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Ejecutar análisis Minervini SEPA completo
      run: |
        echo "Iniciando análisis Minervini SEPA de todas las acciones NYSE + NASDAQ..."
        echo "Sistema: 11 filtros (8 técnicos + 3 fundamentales)"
        echo "Metodología: SEPA de Mark Minervini"
        python script_automated.py
      env:
        PYTHONUNBUFFERED: 1  # Para ver output en tiempo real
        
    - name: Crear JSON para dashboard Minervini
      run: |
        echo "Generando dashboard Minervini con scoring system..."
        python create_dashboard_data.py
        
    - name: Verificar archivos generados
      id: verify_data_file
      run: |
        echo "Verificando la existencia y el contenido de docs/data.json..."
        if [ ! -f docs/data.json ] || [ $(stat -c%s docs/data.json) -lt 200 ]; then
          echo "::error::El archivo data.json no se generó correctamente o está casi vacío."
          exit 1
        fi
        echo "✓ El archivo data.json se generó correctamente. Tamaño: $(stat -c%s docs/data.json) bytes."
    
    - name: Configurar Pages
      uses: actions/configure-pages@v4
      
    - name: Subir artefacto de Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: './docs'
        
    - name: Desplegar a GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      
    - name: Resumen final Minervini
      run: |
        echo "=== MINERVINI SEPA ANALYSIS COMPLETADO ==="
        echo "🎯 Metodología: SEPA de Mark Minervini"
        echo "📊 Filtros aplicados: 11 (8 técnicos + 3 fundamentales)"
        echo "🚀 Dashboard disponible en: ${{ steps.deployment.outputs.page_url }}"
        echo "⏰ Próxima ejecución: Mañana a la misma hora"
        echo "📱 Optimizado para móvil con Stage Analysis y RS Rating"